/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frame;

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

import domain.Publicacao;

/**
 *
 * @author lgfas
 */
public class PublicacaoList extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;
	private List<Publicacao> publicacoesList;

	/**
	 * Creates new form Usuario
	 */
	public PublicacaoList() {
		initComponents();
	}

	/**
	 * Creates new form Usuario
	 */
	public PublicacaoList(List<Publicacao> publicacoesList) {
		initComponents();
		this.publicacoesList = publicacoesList;
		updateModelList(publicacoesList);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		publicacaoType = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		inputBusca = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		listaPublicacoes = new javax.swing.JList<>();
		jLabel6 = new javax.swing.JLabel();
		checkArtigo = new javax.swing.JCheckBox();
		checkLivro = new javax.swing.JCheckBox();
		buscarBtn = new javax.swing.JButton();

		setClosable(true);
		setTitle("Listagem de publicações");

		jLabel1.setText("Busca");

		listaPublicacoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		listaPublicacoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		listaPublicacoes.setFocusable(false);
		listaPublicacoes.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				listaPublicacoesMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(listaPublicacoes);

		jLabel6.setText("Publicações");

		publicacaoType.add(checkArtigo);
		checkArtigo.setText("Artigo");
		checkArtigo.setToolTipText("");

		publicacaoType.add(checkLivro);
		checkLivro.setText("Livro");

		buscarBtn.setText("buscar");
		buscarBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buscarBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(50, 50, 50).addComponent(checkArtigo).addGap(18, 18, 18)
						.addComponent(checkLivro)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(inputBusca))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
								.addComponent(jLabel6).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
										.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(buscarBtn)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(14, 14, 14)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(checkArtigo).addComponent(checkLivro))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(inputBusca, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(buscarBtn)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel6)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		pack();
	}

	private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buscarBtnActionPerformed
		String busca = inputBusca.getText().toLowerCase();
		var publicacoes = publicacoesList.stream().filter(p -> {
			return p.getAutores().stream().anyMatch(autor -> autor.getNome().toLowerCase().contains(busca))
					|| p.getNome().toLowerCase().contains(busca);
		}).toList();

		var listagem = new DefaultListModel<domain.Publicacao>();
		listagem.addAll(publicacoes);
		listaPublicacoes.setModel(listagem);
	}

	@SuppressWarnings("unchecked")
	private void listaPublicacoesMouseClicked(java.awt.event.MouseEvent evt) {
		if (evt.getClickCount() == 1) {
			JList<Publicacao> target = (JList<Publicacao>) evt.getSource();
			int index = target.locationToIndex(evt.getPoint());
			if (index >= 0) {
				Publicacao publicacao = target.getModel().getElementAt(index);
				Integer acao = (new AcoesUsuarioDialog(null, true,
						"Qual operação deseja realizar para o usuário (%s)".formatted(publicacao))).showDialog();
				if (acao == null)
					return;
				switch (acao) {
				case 1:
					var edicaoDialog = new PublicacaoDialog(null, true, publicacao);
					var user = edicaoDialog.showDialog();
					publicacao.clone(user);
					break;
				case 2:
					int input = JOptionPane.showConfirmDialog(null,
							"Deseja realmente exluir a publicação \"%s\"?".formatted(publicacao));
					if (input == 0) {
						publicacoesList.remove(publicacao);
						updateModelList(publicacoesList);
					}
					break;
				case 0:
					break;
				default:
					throw new AssertionError();
				}
			}
		}
	}

	private void updateModelList(List<Publicacao> publics) {
		var listagem = new DefaultListModel<Publicacao>();
		listagem.addAll(publics);
		listaPublicacoes.setModel(listagem);
	}

	private javax.swing.JButton buscarBtn;
	private javax.swing.JCheckBox checkArtigo;
	private javax.swing.JCheckBox checkLivro;
	private javax.swing.JTextField inputBusca;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JList<domain.Publicacao> listaPublicacoes;
	private javax.swing.ButtonGroup publicacaoType;

}
