/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package frame;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import domain.Pessoa;

/**
 *
 * @author lgfas
 */
public class Publicacao extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;

	private domain.Publicacao obj;

	private Function<domain.Publicacao, Void> onFinished;

	/**
	 * Creates new form Usuario
	 */
	public Publicacao() {
		obj = null;
		initComponents();
		this.onFinished = null;
	}

	public Publicacao(Function<domain.Publicacao, Void> callable) {
		obj = null;
		initComponents();
		this.onFinished = callable;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		publicacaoType = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		editora = new javax.swing.JLabel();
		inputNome = new javax.swing.JTextField();
		inputEdicao = new javax.swing.JTextField();
		inputPaginas = new javax.swing.JTextField();
		inputAno = new javax.swing.JTextField();
		inputEditora = new javax.swing.JTextField();
		cadastrarBtn = new javax.swing.JButton();
		cancelBtn = new javax.swing.JButton();
		artigoType = new javax.swing.JRadioButton();
		livroType = new javax.swing.JRadioButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		listaPessoas = new javax.swing.JList<>();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		inputTexto = new javax.swing.JTextArea();
		jLabel7 = new javax.swing.JLabel();
		isbn = new javax.swing.JLabel();
		inputISBNConclusao = new javax.swing.JTextField();
		newAutor = new javax.swing.JLabel();

		jLabel1.setText("Nome");

		jLabel2.setText("Edição");

		jLabel3.setText("Páginas");

		jLabel4.setText("Ano");

		editora.setText("Editora");

		cadastrarBtn.setText("Cadastrar");
		cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cadastrarBtnActionPerformed(evt);
			}
		});

		cancelBtn.setText("Cancelar");
		cancelBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBtnActionPerformed(evt);
			}
		});

		publicacaoType.add(artigoType);
		artigoType.setText("Artigo");
		artigoType.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				artigoTypeItemStateChanged(evt);
			}
		});

		publicacaoType.add(livroType);
		livroType.setSelected(true);
		livroType.setText("Livro");
		livroType.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				livroTypeItemStateChanged(evt);
			}
		});

		listaPessoas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		listaPessoas.setEnabled(false);
		listaPessoas.setFocusable(false);
		jScrollPane1.setViewportView(listaPessoas);

		jLabel6.setText("Autores");

		inputTexto.setColumns(20);
		inputTexto.setRows(5);
		jScrollPane2.setViewportView(inputTexto);

		jLabel7.setText("Texto");

		isbn.setText("ISBN");

		newAutor.setForeground(new java.awt.Color(102, 204, 255));
		newAutor.setText("novo (+)");
		newAutor.setToolTipText("");
		newAutor.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				newAutorMousePressed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(128, 128, 128).addComponent(artigoType)
						.addGap(40, 40, 40).addComponent(livroType)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(inputNome))
								.addGroup(layout.createSequentialGroup().addContainerGap()
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
														.addComponent(cadastrarBtn).addGap(18, 18, 18)
														.addComponent(cancelBtn))
												.addGroup(layout
														.createSequentialGroup()
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel7)
																.addComponent(jScrollPane2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(0, 0, Short.MAX_VALUE))))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(inputEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 112,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel4))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel6)
												.addGap(25, 25, 25).addComponent(newAutor))
										.addGroup(layout.createSequentialGroup().addComponent(editora)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(inputEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(isbn)))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE,
																84, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jLabel3)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(inputPaginas))
												.addGroup(layout.createSequentialGroup()
														.addComponent(inputISBNConclusao,
																javax.swing.GroupLayout.PREFERRED_SIZE, 220,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(0, 0, Short.MAX_VALUE)))))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(14, 14, 14)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(artigoType).addComponent(livroType))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
								.addComponent(inputEdicao, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4)
								.addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3).addComponent(inputPaginas,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(35, 35, 35))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(editora)
								.addComponent(inputEditora, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(isbn).addComponent(inputISBNConclusao,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
						.addComponent(jLabel7).addComponent(newAutor))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
				.addGap(7, 7, 7).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(cancelBtn).addComponent(cadastrarBtn))
				.addContainerGap()));

		pack();
	}

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if (publicacaoType.getSelection() != null) {
				var listPessoas = getListagemModel();
				obj = null;
				if (livroType.isSelected()) {
					obj = new domain.Livro(inputNome.getText(), Integer.parseInt(inputEdicao.getText()),
							Integer.parseInt(inputAno.getText()), listPessoas, inputTexto.getText(),
							Integer.parseInt(inputPaginas.getText()), inputEditora.getText(),
							inputISBNConclusao.getText(), null);
				} else {
					obj = new domain.Artigo(inputNome.getText(), Integer.parseInt(inputEdicao.getText()),
							Integer.parseInt(inputAno.getText()), listPessoas, inputTexto.getText(),
							Integer.parseInt(inputPaginas.getText()), inputEditora.getText(),
							inputISBNConclusao.getText());
				}
				onFinished.apply(obj);
				this.dispose();
			} else {
				JOptionPane.showMessageDialog(Publicacao.this,
						"É necessário selecionar o tipo de publicação a ser cadastrada.");
			}
		} catch (NumberFormatException ex) {
			JOptionPane.showMessageDialog(Publicacao.this, "Erro ao tentar converter a idade para um número.");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(Publicacao.this, "Erro ao executar função onFinished.");
		}
	}

	private void newAutorMousePressed(java.awt.event.MouseEvent evt) {
		var pessoaDialog = new PessoaDialog(null, true);
		var pessoa = pessoaDialog.showDialog();
		if (pessoa != null) {
			var pessoas = getListagemModel();
			pessoas.add(pessoa);
			var listagem = new DefaultListModel<Pessoa>();
			listagem.addAll(pessoas);
			listaPessoas.setModel(listagem);
		}
	}

	private void livroTypeItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_livroTypeItemStateChanged
		if (evt.getStateChange() == ItemEvent.SELECTED) {
			isbn.setText("ISBN");
			editora.setText("Editora");
			editora.setVisible(true);
			inputEditora.setVisible(true);
		}
	}

	private void artigoTypeItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_artigoTypeItemStateChanged
		if (evt.getStateChange() == ItemEvent.SELECTED) {
			isbn.setText("Conclusão");
			editora.setVisible(false);
			inputEditora.setVisible(false);
		}
	}

	private List<domain.Pessoa> getListagemModel() {
		List<domain.Pessoa> listPessoas = new ArrayList<>();
		int size = listaPessoas.getModel().getSize();

		for (int i = 0; i < size; i++) {
			listPessoas.add(listaPessoas.getModel().getElementAt(i));
		}
		return listPessoas;
	}

	public domain.Publicacao showGetObj() {
		setVisible(true);
		return obj;
	}

	private javax.swing.JRadioButton artigoType;
	private javax.swing.JButton cadastrarBtn;
	private javax.swing.JButton cancelBtn;
	private javax.swing.JLabel editora;
	private javax.swing.JTextField inputAno;
	private javax.swing.JTextField inputEdicao;
	private javax.swing.JTextField inputEditora;
	private javax.swing.JTextField inputISBNConclusao;
	private javax.swing.JTextField inputNome;
	private javax.swing.JTextField inputPaginas;
	private javax.swing.JTextArea inputTexto;
	private javax.swing.JLabel isbn;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JList<domain.Pessoa> listaPessoas;
	private javax.swing.JRadioButton livroType;
	private javax.swing.JLabel newAutor;
	private javax.swing.ButtonGroup publicacaoType;
}
