/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package frame;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import domain.Pessoa;
import domain.Publicacao;

/**
 *
 * @author lgfas
 */
public class PublicacaoDialog extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
	Publicacao obj;
    /**
     * Creates new form PessoaDialog
     */
    public PublicacaoDialog(java.awt.Frame parent, boolean modal, Publicacao obj) {
        super(parent, modal);
        initComponents();
        this.obj = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        publicacaoType = new javax.swing.ButtonGroup();
        inputISBNConclusao = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        newAutor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        artigoType = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        livroType = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPessoas = new javax.swing.JList<>();
        editora = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputEdicao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputTexto = new javax.swing.JTextArea();
        inputPaginas = new javax.swing.JTextField();
        inputAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputEditora = new javax.swing.JTextField();
        isbn = new javax.swing.JLabel();
        cadastrarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar pessoa");
        setName("pessoaDialog"); // NOI18N

        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        newAutor.setForeground(new java.awt.Color(102, 204, 255));
        newAutor.setText("novo (+)");
        newAutor.setToolTipText("");
        newAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newAutorMousePressed(evt);
            }
        });

        jLabel2.setText("Edição");

        publicacaoType.add(artigoType);
        artigoType.setText("Artigo");
        artigoType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                artigoTypeItemStateChanged(evt);
            }
        });

        jLabel3.setText("Páginas");

        publicacaoType.add(livroType);
        livroType.setText("Livro");
        livroType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                livroTypeItemStateChanged(evt);
            }
        });

        jLabel4.setText("Ano");

        listaPessoas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaPessoas.setEnabled(false);
        listaPessoas.setFocusable(false);
        jScrollPane1.setViewportView(listaPessoas);

        editora.setText("Editora");

        jLabel6.setText("Autores");

        inputTexto.setColumns(20);
        inputTexto.setRows(5);
        jScrollPane2.setViewportView(inputTexto);

        jLabel7.setText("Texto");

        isbn.setText("ISBN");

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(artigoType)
                .addGap(40, 40, 40)
                .addComponent(livroType)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNome))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cadastrarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(25, 25, 25)
                                .addComponent(newAutor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isbn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputPaginas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputISBNConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artigoType)
                    .addComponent(livroType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(inputAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(inputPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editora)
                        .addComponent(inputEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(isbn)
                        .addComponent(inputISBNConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(newAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(cadastrarBtn))
                .addContainerGap())
        );

        pack();
    }

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void newAutorMousePressed(java.awt.event.MouseEvent evt) {
        var pessoaDialog = new PessoaDialog(null,true);
        var pessoa = pessoaDialog.showDialog();
        if(pessoa != null) {
            var pessoas = getListagemModel();
            pessoas.add(pessoa);
            updateModelList(pessoas);
        }
    }

    private void artigoTypeItemStateChanged(java.awt.event.ItemEvent evt) {
        if(evt.getStateChange() == ItemEvent.SELECTED){
            isbn.setText("Conclusão");
            editora.setVisible(false);
            inputEditora.setVisible(false);
        }
    }

    private void livroTypeItemStateChanged(java.awt.event.ItemEvent evt) {
        if(evt.getStateChange() == ItemEvent.SELECTED){
            isbn.setText("ISBN");
            editora.setText("Editora");
            editora.setVisible(true);
            inputEditora.setVisible(true);
        }
    }

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            var listPessoas = getListagemModel();
            if(livroType.isSelected()){
                obj = new domain.Livro(inputNome.getText(), Integer.parseInt(inputEdicao.getText()), Integer.parseInt(inputAno.getText()),listPessoas, inputTexto.getText(), Integer.parseInt(inputPaginas.getText()), inputEditora.getText(), inputISBNConclusao.getText(), null);
            }else{
                obj = new domain.Artigo(inputNome.getText(), Integer.parseInt(inputEdicao.getText()), Integer.parseInt(inputAno.getText()),listPessoas, inputTexto.getText(), Integer.parseInt(inputPaginas.getText()), inputEditora.getText(), inputISBNConclusao.getText());
            }
            setVisible(false);
            this.dispose();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(PublicacaoDialog.this, "Erro ao tentar converter dados informados para números.");
        }
    }
    
    public Publicacao showDialog() {
        setVisible(true);
        return obj;
    }
    private List<Pessoa> getListagemModel(){
    	List<Pessoa> listPessoas = new ArrayList<>();
        // Get number of items in the list
        int size = listaPessoas.getModel().getSize();

        // Get all item objects
        for (int i = 0; i < size; i++) {
            listPessoas.add(listaPessoas.getModel().getElementAt(i));
        }
        return listPessoas;
    }
    private void updateModelList(List<Pessoa> publics) {
        var listagem = new DefaultListModel<Pessoa>();
        listagem.addAll(publics);
        listaPessoas.setModel(listagem);
    }
    
    private javax.swing.JRadioButton artigoType;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel editora;
    private javax.swing.JTextField inputAno;
    private javax.swing.JTextField inputEdicao;
    private javax.swing.JTextField inputEditora;
    private javax.swing.JTextField inputISBNConclusao;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputPaginas;
    private javax.swing.JTextArea inputTexto;
    private javax.swing.JLabel isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<domain.Pessoa> listaPessoas;
    private javax.swing.JRadioButton livroType;
    private javax.swing.JLabel newAutor;
    private javax.swing.ButtonGroup publicacaoType;
}
